

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /home/debater
    ports:
      - 8000:8000
    volumes:
      - .:/home/debater
    env_file:
      - .env
    environment:
      - MODE=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /home/debater
    entrypoint: pytest
    volumes:
      - .:/home/debater
    env_file:
      - .env
    environment:
      - MODE=testing
      - REDIS_URL=redis://redis:6379

    profiles:
      - test
    depends_on:
      - redis

volumes:
  redis_data:
