version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/debater
    entrypoint: uvicorn debater.app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - .:/home/debater
    environment:
      - MODE=development

  test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/debater
    entrypoint: pytest
    volumes:
      - .:/home/debater
    environment:
      - MODE=testing
    profiles:
      - test
