FROM python:3.8

WORKDIR /home/debater

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

# Install test dependencies
RUN pip install pytest requests redis

COPY . .

EXPOSE 8000

# Development command (with reload)
CMD ["uvicorn", "debater.app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]